### ISSUE TITLE
Is horde equipment Longsword upgrade button missing or maxed out?

### ISSUE THREAD

**Issue by ce51benz** [Tendsty/gooboo#11]
When I upgrade Longsword to the point that raise skill to deal 2900% physical dmg, the upgrade button is hidden. Is this normal or bug or I already maxed? If the equipment upgrade have max level. I suggest to notice player when upgrade reach max level.

![Untitled11](https://github.com/Tendsty/gooboo/assets/8495239/dbcbe3f2-e35f-4c94-926c-77919570e6a7)

**Comment by Tendsty** [comment]
Some equipment items have a maximum level, the upgrade button disappears if that limit is reached.
I'll put a 'maxed' label on the list for the next update

**Comment by ce51benz** [comment]
> Some equipment items have a maximum level, the upgrade button disappears if that limit is reached. I'll put a 'maxed' label on the list for the next update

Thank you very much for clarify this. I will noted.

**Comment by ce51benz** [comment]
Now I see the max label. I will close this issue.
