### ISSUE TITLE
Village : Dequeue pending building in queue

### ISSUE THREAD

**Issue by ce51benz** [Tendsty/gooboo#15]
Is there any way to dequeue pending building in queue? If the queue have too many pending building in queue, it should be frustrating that if I want to build the more important building first or cancel some pending building to refund materials.

<img width="683" alt="Screen Shot 2566-10-14 at 15 29 40" src="https://github.com/Tendsty/gooboo/assets/8495239/99c32822-d14e-4385-a0be-277b548b5b1b">

**Comment by Tendsty** [comment]
Hello, you can drag/drop the buildings in the queue to change their order. There is no option to cancel buildings though

**Comment by ce51benz** [comment]
Oh I never drag the building in queue. I will try that.
