### ISSUE TITLE
"Knock on wood" achievement description/impl incorrect

### ISSUE THREAD

**Issue by d0sboots** [Tendsty/gooboo#16]
The achievement "Knock on wood" has the following description: "Highest wood, plant fiber or stone amount" https://github.com/Tendsty/gooboo/blob/86ae5ae53a056e79324e08a43bf2a0fa8400b3e6/src/lang/en/stat.js#L78 However, the actual achievement is for the *total* of highest wood + highest plant + highest stone amount: https://github.com/Tendsty/gooboo/blob/86ae5ae53a056e79324e08a43bf2a0fa8400b3e6/src/js/modules/village/achievement.js#L7
```js
 basicResources: {value: () => Math.max(
        store.state.stat.village_woodMax.total +
        store.state.stat.village_plantFiberMax.total +
        store.state.stat.village_stoneMax.total
    ), milestones: lvl => Math.pow(10, lvl) * buildNum(10, 'K'), relic: {3: 'sapling'}},
```

**Comment by Tendsty** [comment]
Fixed in v1.3.0
