### ISSUE TITLE
Save file broken after update to v1.3.0

### ISSUE THREAD

**Issue by ce51benz** [Tendsty/gooboo#19]
After update to v1.3.0 the game is not loaded. And when I inspect at console, I got this message even when I try to load save from another browser.

![Untitled11](https://github.com/Tendsty/gooboo/assets/8495239/def5b4d0-a895-493e-b4e1-d067179418c6)

But when I load old save in early global level (Before Horde) it work fine.

**Comment by Tendsty** [comment]
Fixed in v1.3.1
