### ISSUE TITLE
Global level is confusing

### ISSUE THREAD

**Issue by d0sboots** [Tendsty/gooboo#8]
The current tooltip for global level reads: "Based on the sum of multiple values. Used to unlock new features"
Then it lists a number of values, each of them listed as a *maximum*. For instance, "Mining: Deepest ore mine rock broken    46", "Village: Maximum Housing     47", etc.

This gives the impression that the formula for global level is `max(mining_level) + max(village_level) + max(horde_level)`. However, the actual formula is `max(mining_level + village_level + horde_level)`: The highwater mark for those levels reached *at the same time*.

Either the formula should be changed, or the tooltip should make this more clear.

**Comment by d0sboots** [comment]
Hmm, perhaps I am just getting confused by the discrepancy in "Horde: maximum zone". The value in the tooltip seems to be one less than my actual maximum, and also one less than what's shown in the achievement.

**Comment by Tendsty** [comment]
Hi, horde global level is based on the highest zone boss defeated, not highest zone reached. I updates the description, this will be added in the next release

**Comment by Tendsty** [comment]
Added in v1.2.0
